# Generated by Django 5.2.6 on 2025-09-18 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('composer', models.CharField(max_length=200)),
                ('arranger', models.CharField(blank=True, max_length=200, null=True)),
                ('genre', models.CharField(blank=True, choices=[('REL', 'Duchovní'), ('CHO', 'Sborová'), ('JAZ', 'Jazzová'), ('POP', 'Populární'), ('CLA', 'Klasická'), ('SEC', 'Světská'), ('FOL', 'Folklórní')], null=True)),
                ('difficulty_level', models.CharField(blank=True, choices=[(1, 'Velmi snadná'), (2, 'Snadná'), (3, 'Střední'), (4, 'Obtížná'), (5, 'Velmi obtížná')], max_length=1, null=True)),
                ('publication_year', models.IntegerField(blank=True, null=True)),
                ('publisher', models.CharField(blank=True, max_length=200, null=True)),
                ('isbn', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('sheet_file', models.FileField(upload_to='sheets/')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modified_sheets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
