# Generated by Django 5.2.6 on 2025-09-18 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet_music_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='sheet_file',
            field=models.FileField(upload_to=''),
        ),
    ]
