# Generated by Django 5.2.6 on 2025-09-18 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet_music_app', '0002_sheet_public_alter_sheet_sheet_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
