# Generated by Django 5.2.6 on 2025-09-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet_music_app', '0003_sheet_preview_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
