# Generated by Django 5.2.6 on 2025-10-08 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet_music_app', '0004_sheet_slug_delete_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='sheet',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='sheets', to='sheet_music_app.tag'),
        ),
    ]
