# Generated by Django 5.2.6 on 2025-10-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet_music_app', '0005_tag_sheet_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sheet',
            name='difficulty_level',
        ),
        migrations.RemoveField(
            model_name='sheet',
            name='genre',
        ),
        migrations.AddField(
            model_name='sheet',
            name='cast',
            field=models.CharField(blank=True, choices=[('SATB', 'satb'), ('SSATB', 'ssatb'), ('SSAA', 'ssaa'), ('SSAB', 'ssab'), ('SSA', 'ssa'), ('SAT', 'sat'), ('SAB', 'sab')], null=True),
        ),
        migrations.AddField(
            model_name='sheet',
            name='season',
            field=models.CharField(blank=True, choices=[('ADVENT', 'Advent'), ('CHRISTMAS', 'Vánoce'), ('LENT', 'Půst'), ('EASTER', 'Velikonoce'), ('PENTECOST', 'Letnice'), ('HOLY_TRINITY', 'Nejsvětější Trojice'), ('INTERLUDE', 'Mezidobí')], null=True),
        ),
        migrations.AddField(
            model_name='sheet',
            name='use',
            field=models.CharField(blank=True, choices=[('HYMNS', 'Chvalozpěvy'), ('EUCHARIST', 'Eucharistie'), ('HOLY_SPIRIT', 'Duch Svatý'), ('VIRGIN_MARY', 'PANNA MARIA'), ('SAINTS', 'Svatí'), ('WEDDINGS', 'Svatební obřady'), ('FUNERAL', 'Pohřebí obřady')], null=True),
        ),
    ]
