# Generated by Django 5.2.6 on 2025-10-14 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet_music_app', '0006_remove_sheet_difficulty_level_remove_sheet_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='use',
            field=models.CharField(blank=True, choices=[('HYMNS', 'Chvalozpěvy'), ('EUCHARIST', 'Eucharistie'), ('HOLY_SPIRIT', 'Duch Svatý'), ('VIRGIN_MARY', 'Panna Maria'), ('SAINTS', 'Svatí'), ('WEDDINGS', 'Svatební obřady'), ('FUNERAL', 'Pohřebí obřady')], null=True),
        ),
    ]
