# Generated by Django 5.2.6 on 2025-10-16 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet_music_app', '0007_alter_sheet_use'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet',
            name='cast',
            field=models.CharField(blank=True, choices=[('SATB', 'SATB'), ('SSATB', 'SSATB'), ('SSAA', 'SSAA'), ('SSAB', 'SSAB'), ('SSA', 'SSA'), ('SAT', 'SAT'), ('SAB', 'SAB'), ('UNISON', 'Unisono'), ('OTHER', 'Jiné')], null=True),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='season',
            field=models.CharField(blank=True, choices=[('ADVENT', 'Advent'), ('CHRISTMAS', 'Vánoce'), ('LENT', 'Půst'), ('EASTER', 'Velikonoce'), ('PENTECOST', 'Letnice'), ('HOLY_TRINITY', 'Nejsvětější Trojice'), ('INTERLUDE', 'Mezidobí'), ('OTHER', 'Žádné')], null=True),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='use',
            field=models.CharField(blank=True, choices=[('HYMNS', 'Chvalozpěvy'), ('EUCHARIST', 'Eucharistie'), ('HOLY_SPIRIT', 'Duch Svatý'), ('VIRGIN_MARY', 'Panna Maria'), ('SAINTS', 'Svatí'), ('WEDDINGS', 'Svatební obřady'), ('FUNERAL', 'Pohřebí obřady'), ('FOLK', 'Lidové písně'), ('MINE', 'Hornické písně'), ('OTHER', 'Ostatní')], null=True),
        ),
    ]
